check-leaks: false
color: true
diff: true
full-trace: true
reporter: dot
require:
  - 'ts-node/register'
  - 'src/register-cucumber.ts'
spec: './node_modules/@integration/cucumber-specs/spec/**/*.spec.ts'
timeout: 30000
v8-stack-trace-limit: 100
